services:
  mongodb:
    image: mongo:8
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:8-alpine
    restart: unless-stopped

  auth-service:
    build:
      context: ./auth-service
    env_file:
      - ./auth-service/.env.docker
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis

  hackathon-service:
    build:
      context: ./hackathon-service
    env_file:
      - ./hackathon-service/.env.docker
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis

  media-service:
    build:
      context: ./media-service
    env_file:
      - ./media-service/.env.docker
    restart: unless-stopped
    depends_on:
      - mongodb

  notification-service:
    build:
      context: ./notification-service
    env_file:
      - ./notification-service/.env.docker
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis

  chatbot-service:
    build:
      context: ./chatbot-service
    env_file:
      - ./chatbot-service/.env.docker
    restart: unless-stopped

  api-gateway:
    build:
      context: ./api-gateway
    env_file:
      - ./api-gateway/.env.docker
    restart: unless-stopped
    depends_on:
      - auth-service
      - hackathon-service
      - media-service
      - notification-service
      - chatbot-service

  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
    - "80:80"
    - "443:443"
    depends_on:
    - api-gateway
    volumes:
    - ./certbot/conf:/etc/letsencrypt
    - ./certbot/www:/var/www/certbot

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    env_file:
      - ./grafana/.env.docker
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=https://rahul1901.prometeo.in/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    ports:
      - "127.0.0.1:3001:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro

volumes:
  mongo_data:
  prometheus_data:
  grafana_data: