version: "3.9"

services:
  mongodb:
    image: mongo:8
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:8-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    env_file:
      - ./auth-service/.env
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
      - redis

  hackathon-service:
    build:
      context: ./hackathon-service
    container_name: hackathon-service
    env_file:
      - ./hackathon-service/.env
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
      - redis

  media-service:
    build:
      context: ./media-service
    container_name: media-service
    env_file:
      - ./media-service/.env
    ports:
      - "5003:5003"
    depends_on:
      - mongodb

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    env_file:
      - ./notification-service/.env
    ports:
      - "5005:5005"
    depends_on:
      - mongodb
      - redis

volumes:
  mongo_data: