version: "3.9"

services:
  mongodb:
    image: mongo:8
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:8-alpine
    restart: unless-stopped

  auth-service:
    build:
      context: ./auth-service
    env_file:
      - ./auth-service/.env.docker
    expose:
      - "5001"
    depends_on:
      - mongodb
      - redis

  hackathon-service:
    build:
      context: ./hackathon-service
    env_file:
      - ./hackathon-service/.env.docker
    expose:
      - "5002"
    depends_on:
      - mongodb
      - redis

  media-service:
    build:
      context: ./media-service
    env_file:
      - ./media-service/.env.docker
    expose:
      - "5003"
    depends_on:
      - mongodb

  notification-service:
    build:
      context: ./notification-service
    env_file:
      - ./notification-service/.env.docker
    expose:
      - "5004"
    depends_on:
      - mongodb
      - redis

  chatbot-service:
    build:
      context: ./chatbot-service
    env_file:
      - ./chatbot-service/.env.docker
    expose:
      - "5005"

  api-gateway:
    build:
      context: ./api-gateway
    env_file:
      - ./api-gateway/.env.docker
    ports:
      - "5000:5000"
    depends_on:
      - auth-service
      - hackathon-service
      - media-service
      - notification-service
      - chatbot-service

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    depends_on:
      - api-gateway
      - auth-service
      - hackathon-service
      - media-service
      - notification-service
      - chatbot-service

  grafana:
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api-gateway

volumes:
  mongo_data:
  prometheus_data:
  grafana_data:
