version: "3.9"

services:
  mongodb:
    image: mongo:8
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:8-alpine
    restart: unless-stopped

  auth-service:
    build:
      context: ./auth-service
    env_file:
      - ./auth-service/.env.docker
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis

  hackathon-service:
    build:
      context: ./hackathon-service
    env_file:
      - ./hackathon-service/.env.docker
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis

  media-service:
    build:
      context: ./media-service
    env_file:
      - ./media-service/.env.docker
    restart: unless-stopped
    depends_on:
      - mongodb

  notification-service:
    build:
      context: ./notification-service
    env_file:
      - ./notification-service/.env.docker
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis

  api-gateway:
    build:
      context: ./api-gateway
    env_file:
      - ./api-gateway/.env.docker
    restart: unless-stopped
    depends_on:
      - auth-service
      - hackathon-service
      - media-service
      - notification-service
      
  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
    - "80:80"
    - "443:443"
    depends_on:
    - api-gateway
    volumes:
    - ./certbot/conf:/etc/letsencrypt
    - ./certbot/www:/var/www/certbot

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  mongo_data:
  prometheus_data:
  grafana_data:
